### ISSUE TITLE
TimeSeriesParameterValue to return NaN for invalid index?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineInterface.jl#101]
It seems to me that it would be more convenient to return NaN when accessiting a time series with a "timestamp" that's not in the time series. We return nothing at the moment, which seems ok, but the problem is we also return nothing when a parameter is not specified for a certain entity. It would be very convenient to be able to distinguish between the two cases.

We could do it at the moment thanks to the _default keyword argument in the Parameter call definition, which allows specifying the value to return in case the parameter is not specified for a given entity. As a user, or client package, one could pass something like `missing` as the `_default`, and in that case we could write the code that handles that missing in all different places.

But that feels more artificial. Returning NaN from the time series is better in the sense that time-series already are allowed to hold NaN explicitely (and NaN is also already interpreted as a signal to free a JuMP variable that was previously fixed).

I will just go ahead and do the change, but please @Tasqu for instance, do you think that this could be detrimental in some way?

**Edit**: to provide more context, what I'm trying to do is setup a Map from analysis time to time series, for the fix_node_state in SpineOpt. The idea is each window will fix the node_state for a different timestamp. But for this to work in the current implementation, I would have to specify NaN for the timestamp that got fixed in the previous window, so it gets unfixed. I don't want to do that (I don't want to ask the users to do that), I just want to specify the timestamp I want to fix and nothing else. So if the time series would return NaN for any timestamp I don't specify, I would get what I want (without actually needing to specify the NaN).

**Comment by DillonJ** [comment]
This feels like good change.

Will this change the behaviour when, for example, a value for unit_availability_factor is requested past the last timeseries value. Currently the nothing that results will usually result in an error, usually a method error that you can multiply a float by a nothing.

**Comment by manuelma** [comment]
> Currently the nothing that results will usually result in an error, usually a method error that you can multiply a float by nothing.

I need to check that we still see an error of sorts with NaN instead of nothing. That's important for the last window check in SpineOpt.

**Comment by manuelma** [comment]
I just confirmed that NaN also raises an error when trying to use it in any JuMP expressions, so that's good.
