### ISSUE TITLE
Export input data to GAMS

### ISSUE THREAD

**Issue by Alireza64z** [spine-tools/SpineInterface.jl#109]
Hello,

I'm interested in using GAMS software as a spine optimization engine, and I'm seeking guidance on configuring the exporter and importer settings. Specifically, I'm looking for instructions on how to read input parameters and map them in GDX files. For instance, could you provide guidance on how to set the mapping specification for parameters such as demand or capacity? Your assistance in this matter would be greatly appreciated.

**Comment by jkiviluo** [comment]
This is wrong repository for this. SpineInterface is for Julia. So, closing.
