### ISSUE TITLE
`TimeSeries` `repeat` flag should be used carefully.

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/SpineInterface.jl#68]
At the moment, the `repeat` flag in the `TimeSeries` basically requires that the first and last values of the `TimeSeries` are identical. However, this is not enforced on `SpineInterface` level, as the `repeat` property comes through `SpineDBAPI`.

When a `repeat` `TimeSeries` is accessed via a `DateTime` matching it's last timestamp, the value on its first timestamp is used instead. This causes some weird behaviour for `TimeSeries` arithmetic where 
```
ts + ts != ts * 2
```
if the first and last values are not identical.

I'm not sure how to fix this issue, or if it is really a programming issue to begin with. The concept of a `repeat` `TimeSeries` needs further thought. See the [wiki](https://github.com/Spine-project/SpineInterface.jl/wiki/Time-dependent-data-and-data-arithmetic%3F) for further discussion.

**Comment by DillonJ** [comment]
Sounds like a `>=` vs a `>`  issue... in other words...
>When a repeat TimeSeries is accessed via a DateTime matching it's last timestamp, the value on its first timestamp is used
... in this case it should return the value of that time stamp, since as you describe it here, there should be a value. However, for the next timestamp, it should revert to the first?

Or have I misunderstood?

**Comment by Tasqu** [comment]
>Sounds like a >= vs a > issue... in other words...

It's a bit more problematic than that. Since the `TimeSeries` is just a list of `DateTimes` and values, the timesteps don't have a defined length. Essentially, this results in the first and last `DateTimes` overlapping in time.

E.g. accessing a `repeat` `TimeSeries` immediately after the last timestamp determines that the `TimeSeries` should repeat, and accesses the last valid value, which is now the first value. However, accessing the `TimeSeries` immediately before the last timestamp accesses the last valid value again, which is the second-to-last value.

The only point the value at the last timestamp would be accessed is by calling it exactly, but currently `SpineInterface` interprets it as the first timestamp of a new repetition, since the two timestamps overlap in time.

This actually results in a bug when aggregating values over the `repeat` boundary, as it is the only time the last value of a `repeat` `TimeSeries` is currently accessed. Both the last and first timestamps are included in any `TimeSlice` that goes over the `repeat` boundary, and thus both values are included in the aggregation despite them overlapping in time.

**Comment by Tasqu** [comment]
Closing this as old. I believe this hasn't been addressed, and is still an issue with the `repeat` flag. However, I don't think there is an easy fix for this without redesigning the `TImeSeries` to contain more information.
