### ISSUE TITLE
Add `alternative` keyword for the `import_data()` function.

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/SpineInterface.jl#80]
Currently, the `import_data(url, data, comment)` function can be used to import e.g. `ObjectClass` or `RelationshipClass` objects into the database at `url`. However, there's no way to tweak which alternative the included parameter values are attributed to, and by default everything gets put into its own automatically created alternative. This can cause unnecessary bloat in databases with repeated imports, so it could be useful to be able to force importing into a specific alternative, e.g. "Base".

The `update_import_data!()` and `write_parameters()` functions already deal with alternatives, so doing something similar with `import_data()` shouldn't be too difficult. I hope.

**Comment by manuelma** [comment]
Maybe we can have another function for that, and keep `import_data` low level as it is (a mirror of the same function in spinedb_api)

**Comment by Tasqu** [comment]
>Maybe we can have another function for that, and keep import_data low level as it is (a mirror of the same function in spinedb_api)

Are you sure you're not referring to `_import_data()`? I already added the method for
```julia
import_data(
    url::String,
    data::Union{ObjectClass,RelationshipClass},
    comment::String
)
```
back in the day, and if that's similar to what's found in spinedb_api, that was pure coincidence 😄 It's using the `_to_dict()` function to convert the `ObjectClass` and `RelationshipClass` to the `Dict` representation, so is it that big of a deal to add `alternative` as a keyword to the mix?

**Comment by manuelma** [comment]
We have 
```
import_data(url::String, data::Dict, comment::String)
```
which I believe was the original function to import data and commit. The method you refer to is just extending the original function to deal with `Union{ObjectClass,RelationshipClass}` as second argument.

**Comment by Tasqu** [comment]
Closing this as old. While the `import_data` function doesn't contain an easy-to-use keyword for the alternative, the `data` `Dict` that is imports does support `alternative` information. Essentially, this can already be done through `SpineInterface`, but not in a trivial manner.
