### ISSUE TITLE
TimePattern-TimePattern arithmetic

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineInterface.jl#90]
We need this for SpineOpt's LODF calculation. Since the PTDF is now time varying (to account for transmission-line outages occurring sparingly in time), and the LODF are calculated by subtracting two PTDFs, then we may encounter a TimePattern-TimePattern operation where the keys of the operands may differ.

**Comment by manuelma** [comment]
Here is an example of what I did:

```
tp1 = {"M1-3,M7-12": a, "M4-6" => b)

tp2 = {"WD1-5": c, "WD6-7" => d)

tp1 + tp2 == {
    "M1-3;WD1-5": a + c,
    "M1-3;WD6-7": a + d,
    "M4-6;WD1-5": b + c,
    "M4-6;WD6-7": b + d,
    "M7-12;WD1-5": a + c,
    "M7-12;WD6-7": a + d,
}
```

**Comment by DillonJ** [comment]
Very nice - complex stuff

**Comment by manuelma** [comment]
Done, please reopen if problematic.
