### ISSUE TITLE
Rudimentary `Map` arithmetic?

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/SpineInterface.jl#92]
I'll most likely be needing rudimentary arithmetic for `Map`s for processing updating stochastic weather data for my building modelling stuff. I thought I'd create this issue as a heads-up and ask for some input.

## `Map` and `{Number, TimeSeries, TimePattern}` operations shouldn't be an issue.

The overall algorithm should be pretty straightforward: Create a new `Map` with the same indices, loop over them, and perform the desired operation between the corresponding value of the `Map` and the other operand. This should work for nested `Map`s as well, since the same method is just repeated until eventually a non-`Map` value is found.

However...

## How to handle operations between two `Map`s?

The big question. The way I see it, there are two potential ways to handle this:

1. **Check that both `Map`s have identical indices, and throw an error if not.** Otherwise, just perform the desired operation for all of the indices as above.
2. Create a new `Map` containing the indices from both `Map`s, and perform the desired operation only for the overlapping indices, and preserve the original values for the rest.

Option 1 is probably safer, as it forces the user to know what they are doing. However, I can see it potentially resulting in quite a few annoying error messages when setting stuff up. Option 2 would be more lenient, but there is some ambiguity how the cases with mismatched indices should be handled. Furthermore, it could result in accidentally processing huge amounts of useless data.

Any thoughts? @DillonJ @manuelma @mihlema @jkiviluo 

I'll probably start experimenting with implementing option 1 to see if I can get it to do what I need it to do.

**Comment by manuelma** [comment]
This is what I did recently for time-patterns with arbitrary indices:

```julia
keys = []
values = []
for (key1, value1) in map1
    for (key2, value2) in map2
        result_key =  combine(key1, key2)  # combine keys somehow
        result_key === nothing && continue
        push!(keys, result_key)
        push!(values, f(value1, value2))   # perform the operation between values
    end
end
Map(keys, values)
```

So all the complexity is in the `combine`  function that takes two keys and returns the key of the result. If the two keys are indentical, it should return the same key. If the do not overlap at all, it should return nothing so we skip that combination. And if they do overlap, it should return a new key that corresponds to the overlap.

Is the above correct?

**Comment by Tasqu** [comment]
@manuelma Oh cool, I hadn't noticed that you had implemented something for `TimePattern`-`TimePattern`! But yeah, the idea is basically the same.

However, I'm not sure if we can generalise the rules of `combine` for `Map`s, as they are inherently more multi-purpose than `TimePattern`s. I guess we could also just omit non-overlapping indices altogether when creating the new `Map`, but I'm not sure if that's better than erroring.
