### ISSUE TITLE
Can't find the right value for a parameter defined in multiple classes

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineInterface.jl#93]
Say a parameter is defined in two classes, one with dimensions A, B and C, and the other with dimensions A and B. If you try to access it specifying dimensions A, B and C, SpineInterface might find first the value for dimensions A and B and return it as valid, before looking into the class with all three dimensions.

I think SpineInterface should start looking at the class with most dimensions first to avoid this type of pitfalls.

**Comment by DillonJ** [comment]
Wouldn't the safest thing to do here be to look only in classes for which the parameter is defined?

**Comment by manuelma** [comment]
We do that actually. We look in all classes where the parameter is defined. Whenever we find a value that matches all the arguments, we use it and stop looking. This means that some of the 'entity arguments' (node, unit, etc) might be interpreted as 'parameter value arguments' (analysis_time, stochastic_scenario, t, etc.) if the class is defined in only a subset of the entity arguments. In your db, you had connection__to_node defined on connection, node and direction, as well as connection__node defined only on connection and node. When trying to access the connection_capacity with connection, node and direction, it first found the value for connection and node only, and thought direction was one of the arguments to pass to the parameter value itself. Hence the error.

Now we look at classes in decreasing order of dimensionality which means that no entity arguments can be ignored as above. Does that make sense?
